// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'idCopyButton': string;
  'idCopyButtonRow': string;
  'idLabel': string;
  'link': string;
  'linkGroup': string;
  'linkLabel': string;
  'links': string;
}
export const cssExports: CssExports;
export default cssExports;
